local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>ff', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>ff', '<cmd> Telescope find_files<CR>')
-- vim.keymap.set('n', '<leader>fw', '<cmd> Telescope live_grep <CR>')
-- vim.keymap.set('n', '<leader>fb', '<cmd> Telescope buffers <CR>')
-- vim.keymap.set('n', '<leader>fh', '<cmd> Telescope help_tags <CR>')
